In [1]:
import pandas as pd

In [ ]:
df = pd.read_csv("../data/ArchiveII.csv")
df

,id,sequence,structure,base_pairs,len
0,5s_Acholeplasma-laidlawii-1,UCUGGUGACGAUAGGUAAGAUGGUUCACCUGUUCCCAUCCCGAACA...,((((((((......((((((((....((((((.............)...,"[[1, 111], [2, 110], [3, 109], [4, 108], [5, 1...",112
1,5s_Acidovorax-temperans-1,UGCCUGAUGACCAUAGCAAGUUGGUACCACUCCUUCCCAUCCCGAA...,.(((((((((.....((((((((.....((((((...............,"[[2, 115], [3, 114], [4, 113], [5, 112], [6, 1...",115
2,tmRNA_Stre.gord._TRW-29390_1-349,GGGGUCGUUACGGAUUCGACAGGCAUUAUGAGGCAUAUUUUGCGAC...,(((((((............((((((((....(((((((((..((((...,"[[1, 345], [2, 344], [3, 343], [4, 342], [5, 3...",349
3,tRNA_tdbR00000055-Schizosaccharomyces_pombe-48...,UCCGUUGUGGUCCAACGGCUAGGAUUCGUCGCUUUCACCGACGGGA...,(((((((..((((........))))((((((.......)))))).....,"[[1, 71], [2, 70], [3, 69], [4, 68], [5, 67], ...",75
4,srp_List.mono._U15684,UGGGUUGAUGAGCGUGAAGCCUUCGCUCGGUUGGAUUUUUCUUCAU...,.(.((((...(.(.((.(.((..(.....)..)).)...(...(.....,"[[2, 276], [4, 274], [5, 273], [6, 272], [7, 2...",279
...,...,...,...,...,...
3859,5s_Bacillus-cereus-6,UGGUAAUGAUGGCAGAGAGGUCACACCCGUUCCCAUACCGAACACG...,((((((.....((((((((.....((((((.............)))...,"[[1, 111], [2, 110], [3, 109], [4, 108], [5, 1...",114
3860,srp_Myco.aviu._AE016958,GGGGACCCCGCGCACCCGACAGAGCCCGUUGACCCUUGCUGCCUUC...,((((.....(.(...(.(.....(.(....).).....).).).)....,"[[1, 53], [2, 52], [3, 51], [4, 50], [10, 45],...",88
3861,tmRNA_Heli.pylo._AE001503_1-383,GGGGCUGACUUGGAUUUCGACAGAUUUCUUGUCGCACAGAUAGCAU...,(((((((.............((((..((((((((.((((((...((...,"[[1, 382], [2, 381], [3, 380], [4, 379], [5, 3...",383
3862,5s_Triticum-aestivum-1,GGAUGCGAUCAUACCAGCACUAAAGCACCGGAUCCCAUCAGAACUC...,(((((((((....(((((((......((((((............))...,"[[1, 118], [2, 117], [3, 116], [4, 115], [5, 1...",120
3863,5s_Streptomyces-violaceus-1,GUUUCGGUGGUCAUAGCGUUAGGGAAACGCCCGGUUACAUUCCGAA...,((.(((((((.....(((..(((.....((((((...............,"[[1, 119], [2, 118], [4, 117], [5, 116], [6, 1...",120

In [15]:
df2 = pd.read_csv("../results/ArchiveII_famfold.csv")
df2.query('method == "sincFold"')

,id,dataset_name,folding,method,family
15456,grp1_a.I1.m.M.grisea.B2.ND1,ArchiveII,"[[2, 38], [4, 36], [5, 35], [9, 32], [10, 30],...",sincFold,grp1
15457,grp1_a.I1.e.P.inouyei.C1.SSU.1506,ArchiveII,"[[3, 403], [14, 30], [15, 29], [16, 28], [17, ...",sincFold,grp1
15458,grp1_a.I1.e.C.saxonicum.C1.SSU.1506,ArchiveII,"[[3, 439], [4, 420], [9, 413], [10, 412], [12,...",sincFold,grp1
15459,grp1_b.I1.e.M.anisopliae.3.C1.LSU.1921,ArchiveII,"[[3, 393], [6, 390], [7, 389], [18, 45], [20, ...",sincFold,grp1
15460,grp1_a.I1.e.G.planctonica.C1.SSU.943,ArchiveII,"[[4, 457], [32, 44], [33, 43], [34, 42], [35, ...",sincFold,grp1
...,...,...,...,...,...
19315,16s_C.reinhardtii.chloro_domain2,ArchiveII,"[[7, 21], [8, 20], [10, 18], [11, 17], [28, 94...",sincFold,16s
19316,16s_M.polymorpha_domain4,ArchiveII,"[[2, 32], [3, 31], [4, 30], [24, 69], [26, 54]...",sincFold,16s
19317,16s_A.fulgidus_domain3,ArchiveII,"[[2, 481], [10, 146], [11, 145], [12, 310], [1...",sincFold,16s
19318,16s_G.intestinalis_domain4,ArchiveII,"[[7, 24], [8, 22], [9, 21], [10, 20], [11, 19]...",sincFold,16s
19319,16s_T.maritima_domain3,ArchiveII,"[[2, 404], [3, 403], [4, 402], [5, 401], [6, 2...",sincFold,16s

In [ ]:
import os
import pandas as pd

out_path = f"data/"
# os.mkdir(out_path)

# read dataset and predefined partitions (the files are available in this repository)
dataset = pd.read_csv("data/ArchiveII_with_prob_and_motiv.csv", index_col="id")
# partitions = pd.read_csv("data/ArchiveII_splits.csv")

In [24]:
fams = dataset["family"].unique()
fams

array(['5s', 'tmRNA', 'tRNA', 'srp', 'grp1', 'RNaseP', '23s',
       'telomerase', '16s'], dtype=object)

In [29]:
for f in fams:
    dataset.loc[dataset["family"] != f].to_csv(out_path + "train_" + f + ".csv")
    dataset.loc[dataset["family"] == f].to_csv(out_path + "test_" + f + ".csv")

In [2]:
from sincfold.dataset import SeqDataset, pad_batch
from torch.utils.data import DataLoader
import pandas as pd

In [7]:
df = pd.read_csv(file1)
df

,id,sequence,structure,base_pairs,len
0,16s_A.fulgidus_domain2,UUUAUUGGGCCUAAAGCGUCCGUAGCCGGGCUGGUAAGUCCUCCGG...,.......(((<<...(.((((.(.(((.(((((((.((((((((((...,"[[8, 329], [9, 328], [10, 327], [11, 312], [12...",359
1,16s_A.fulgidus_domain3,AAGGAAUUGGCGGGGGAGCACUACAACGGGUGGAGCCUGCGGUUUA...,.......(((((.(((((((..((..((((((.((((((((((......,"[[8, 487], [9, 486], [10, 484], [11, 483], [12...",488
2,16s_A.pyrophilus_domain2,UCACUGGGCGUAAAGCGUCCGCAGCCGGUCGGGUAAGCGGGAUGUC...,................((((...(((.(((((((.(((((((((((...,"[[17, 204], [18, 203], [19, 202], [20, 201], [...",250
3,16s_A.pyrophilus_domain4,CCGCCCGUCACGCCACGGAAGUCGGUCCGGCCGGAAGUCCCCGAGC...,..(..((...((((.(((..((((((((((((....(.((((..((...,"[[3, 114], [6, 110], [7, 109], [11, 104], [12,...",137
4,16s_B.subtilis_domain2,AUUAUUGGGCGUAAAGGGCUCGCAGGCGGUUUCUUAAGUCUGAUGU...,.......(((<<.....((((.(.(((.(((((((.(((((((((....,"[[8, 325], [9, 324], [10, 323], [11, 308], [12...",355
...,...,...,...,...,...
432,tmRNA_uncu.bact._TRW-383630-1_1-364,GGGGGUGACCCCGGUUUCGACGUGGGUUACAAAGCAGUGCAGGGGC...,(((((((.............((((((((.....((((..(((...(...,"[[1, 360], [2, 359], [3, 358], [4, 357], [5, 3...",364
433,tmRNA_uncu.bact._TRW-72274-1_1-359,GGGGAUGUUAUUGGCUUCGACGCCGAUGAUGAAGCUCAUAGAUGCA...,(((((((.............((((((((.(...((((...((((((...,"[[1, 355], [2, 354], [3, 353], [4, 352], [5, 3...",359
434,tmRNA_uncu.bact._TRW-72274-2_1-359,GGGGAUGUUCUGGCUUCGACGCUGGUGAUGAAACUCAAUGAUGCAU...,(((((((............((((((((.(....((((..(((.(((...,"[[1, 355], [2, 354], [3, 353], [4, 352], [5, 3...",359
435,tmRNA_uncu.bact._TRW-80840-3_1-379,GGGGCUGCCCUGGUUUCGACGUGGGUUCGGAAUCGGCGUGGUGCAU...,(((((((............((((((((....(((((.((((..(((...,"[[1, 375], [2, 374], [3, 373], [4, 372], [5, 3...",379
436,tmRNA_uncu.mari._TRW-363180_1-347,GGGGGCGAAUAGGGUUCGACGUUUCUACUGGACUCCGAAGCGCAUG...,(((((((............((((..(.((...(..(.((...((((...,"[[1, 343], [2, 342], [3, 341], [4, 340], [5, 3...",347

In [ ]:
file1 = "/home/gkulemeyer/Documents/Repos/sincFold/fam_sim/data/rnadist/dist_100/train_srp.csv"
file2 = "/home/gkulemeyer/Documents/Repos/sincFold/fam_sim/data/rnadist/dist_200/train_srp.csv"
file3 = "/home/gkulemeyer/Documents/Repos/sincFold/fam_sim/data/rnadist/dist_400/train_srp.csv"

files = [
    file1,
    file2,
    file3,
]
for train_file in files:
    data = pd.read_csv(train_file)

    batch_size = 4
    train_loader = DataLoader(
        SeqDataset(train_file, training=True),
        batch_size=batch_size,
        shuffle=True,
        num_workers=2,
        collate_fn=pad_batch,
    )
    steps = 1000
    ep = int(round(steps / len(train_loader)))
    print(f"file:{train_file}, shape: {data.shape}")
    print(
        f"steps: {steps}, lt: {len(train_loader)}, frac: {steps / len(train_loader)}, ep: {ep}"
    )

file:/home/gkulemeyer/Documents/Repos/sincFold/fam_sim/data/rnadist/dist_100/train_srp.csv, shape: (472, 5)
steps: 1000, lt: 107, frac: 9.345794392523365, ep: 9
file:/home/gkulemeyer/Documents/Repos/sincFold/fam_sim/data/rnadist/dist_200/train_srp.csv, shape: (792, 5)
steps: 1000, lt: 179, frac: 5.58659217877095, ep: 6
file:/home/gkulemeyer/Documents/Repos/sincFold/fam_sim/data/rnadist/dist_400/train_srp.csv, shape: (1432, 5)
steps: 1000, lt: 323, frac: 3.0959752321981426, ep: 3

In [ ]:
file1 = "/home/gkulemeyer/Documents/Repos/sincFold/fam_sim/data/rnadist/dist_100/train_23s.csv"
file2 = "/home/gkulemeyer/Documents/Repos/sincFold/fam_sim/data/rnadist/dist_200/train_23s.csv"
file3 = "/home/gkulemeyer/Documents/Repos/sincFold/fam_sim/data/rnadist/dist_400/train_23s.csv"

files = [
    file1,
    file2,
    file3,
]
for train_file in files:
    data = pd.read_csv(train_file)
    batch_size = 4
    train_loader = DataLoader(
        SeqDataset(train_file, training=True),
        batch_size=batch_size,
        shuffle=True,
        num_workers=2,
        collate_fn=pad_batch,
    )
    steps = 1000
    ep = int(round(steps / len(train_loader)))
    print(f"file:{train_file}, shape: {data.shape}")
    print(
        f"steps: {steps}, lt: {len(train_loader)}, frac: {steps / len(train_loader)}, ep: {ep}"
    )

file:/home/gkulemeyer/Documents/Repos/sincFold/fam_sim/data/rnadist/dist_100/train_23s.csv, shape: (437, 5)
steps: 1000, lt: 99, frac: 10.1010101010101, ep: 10
file:/home/gkulemeyer/Documents/Repos/sincFold/fam_sim/data/rnadist/dist_200/train_23s.csv, shape: (846, 5)
steps: 1000, lt: 191, frac: 5.2356020942408374, ep: 5
file:/home/gkulemeyer/Documents/Repos/sincFold/fam_sim/data/rnadist/dist_400/train_23s.csv, shape: (1566, 5)
steps: 1000, lt: 353, frac: 2.8328611898016995, ep: 3